<a href="https://colab.research.google.com/github/abhay-ny/6thSem-ML-Lab/blob/main/1BM24CS400_Lab_1_ML_DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#_ML_DataPreprocessing
from google.colab import files

uploaded = files.upload()

Saving adult.csv to adult.csv
Saving Dataset of Diabetes .csv to Dataset of Diabetes .csv

In [ ]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
for column in df.columns:
    if df[column].dtype != 'object':
        df[column].fillna(df[column].mean(), inplace=True)
    else:
        df[column].fillna(df[column].mode()[0], inplace=True)

/tmp/ipython-input-2340376238.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)

In [ ]:
# Handling Categorical Data
categorical_cols = df.select_dtypes(include='object').columns
categorical_cols
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [ ]:
# ---------------------------------
# Import libraries
# ---------------------------------
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder


# ---------------------------------
# Load Diabetes dataset
# ---------------------------------
diabetes = pd.read_csv('Dataset of Diabetes .csv')


# ---------------------------------
# 1. DATA CLEANING
# ---------------------------------

# (a) Handling Missing Values

# Numerical columns -> mean
num_cols = diabetes.select_dtypes(include=['int64', 'float64']).columns
diabetes[num_cols] = diabetes[num_cols].fillna(diabetes[num_cols].mean())

# Categorical columns -> mode
cat_cols = diabetes.select_dtypes(include='object').columns
for col in cat_cols:
    diabetes[col] = diabetes[col].fillna(diabetes[col].mode()[0])


# (b) Handling Categorical Data (Label Encoding)
le = LabelEncoder()
for col in cat_cols:
    diabetes[col] = le.fit_transform(diabetes[col])


# (c) Handling Outliers (IQR Method)
Q1 = diabetes.quantile(0.25)
Q3 = diabetes.quantile(0.75)
IQR = Q3 - Q1

diabetes = diabetes[~((diabetes < (Q1 - 1.5 * IQR)) |
                      (diabetes > (Q3 + 1.5 * IQR))).any(axis=1)]


# ---------------------------------
# 2. DATA TRANSFORMATION
# ---------------------------------

# (a) Min-Max Normalization
minmax = MinMaxScaler()
diabetes_minmax = minmax.fit_transform(diabetes)
diabetes_minmax_df = pd.DataFrame(diabetes_minmax, columns=diabetes.columns)


# (b) Standard Scaling
standard = StandardScaler()
diabetes_std = standard.fit_transform(diabetes)
diabetes_std_df = pd.DataFrame(diabetes_std, columns=diabetes.columns)

In [ ]:
diabetes.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
169,714,34268,1,45,3.6,80,5.0,6.1,3.7,0.7,3.9,1.7,22.0,3
170,87,24000,0,50,4.0,56,13.7,4.4,2.0,1.0,2.5,0.9,29.0,3
171,231,14389,0,50,4.0,56,13.7,4.4,2.0,1.0,2.5,0.9,29.0,3
172,505,23044,0,48,4.0,38,6.5,4.4,2.3,1.3,2.2,1.0,23.0,3
174,7,34278,0,46,3.0,59,5.1,5.7,3.8,1.3,2.8,1.7,24.0,3

In [ ]:
diabetes.isnull().sum()

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

In [ ]:
diabetes.shape

(556, 14)

In [ ]:
diabetes_minmax_df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,0.892231,0.452186,0.5,0.193548,0.328947,0.690476,0.230769,0.694915,0.723404,0.2,0.673469,0.761905,0.15,0.0
1,0.106516,0.316206,0.0,0.354839,0.381579,0.404762,0.900000,0.406780,0.361702,0.4,0.387755,0.380952,0.50,0.0
2,0.286967,0.188926,0.0,0.354839,0.381579,0.404762,0.900000,0.406780,0.361702,0.4,0.387755,0.380952,0.50,0.0
3,0.630326,0.303545,0.0,0.290323,0.381579,0.190476,0.346154,0.406780,0.425532,0.6,0.326531,0.428571,0.20,0.0
4,0.006266,0.452318,0.0,0.225806,0.250000,0.440476,0.238462,0.627119,0.744681,0.6,0.448980,0.761905,0.25,0.0

In [ ]:
diabetes_std_df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,1.634136,0.322377,0.947475,-2.344564,-0.661056,1.293338,-1.688590,1.126537,1.485468,-1.284433,1.348145,1.482732,-2.141359,0.0
1,-1.060798,-0.421699,-1.040434,-1.280766,-0.395535,-0.104775,2.040328,-0.410418,-0.195241,-0.352859,-0.059949,-0.268049,-0.394447,0.0
2,-0.441866,-1.118165,-1.040434,-1.280766,-0.395535,-0.104775,2.040328,-0.410418,-0.195241,-0.352859,-0.059949,-0.268049,-0.394447,0.0
3,0.735825,-0.490976,-1.040434,-1.706285,-0.395535,-1.153359,-1.045673,-0.410418,0.101355,0.578715,-0.361683,-0.049201,-1.891800,0.0
4,-1.404650,0.323102,-1.040434,-2.131805,-1.059337,0.069989,-1.645729,0.764900,1.584333,0.578715,0.241786,1.482732,-1.642241,0.0

In [ ]:
diabetes_minmax_df.min(), diabetes_minmax_df.max()

(ID           0.0
 No_Pation    0.0
 Gender       0.0
 AGE          0.0
 Urea         0.0
 Cr           0.0
 HbA1c        0.0
 Chol         0.0
 TG           0.0
 HDL          0.0
 LDL          0.0
 VLDL         0.0
 BMI          0.0
 CLASS        0.0
 dtype: float64,
 ID           1.0
 No_Pation    1.0
 Gender       1.0
 AGE          1.0
 Urea         1.0
 Cr           1.0
 HbA1c        1.0
 Chol         1.0
 TG           1.0
 HDL          1.0
 LDL          1.0
 VLDL         1.0
 BMI          1.0
 CLASS        0.0
 dtype: float64)

In [ ]:
diabetes_std_df.mean(), diabetes_std_df.std()

(ID           6.709261e-17
 No_Pation    1.246006e-16
 Gender       1.230031e-16
 AGE         -3.003193e-16
 Urea        -2.140574e-16
 Cr           1.405750e-16
 HbA1c        5.367409e-16
 Chol         8.945682e-17
 TG           2.044727e-16
 HDL         -1.150159e-16
 LDL          2.300318e-16
 VLDL         1.150159e-16
 BMI          4.920125e-16
 CLASS        0.000000e+00
 dtype: float64,
 ID           1.0009
 No_Pation    1.0009
 Gender       1.0009
 AGE          1.0009
 Urea         1.0009
 Cr           1.0009
 HbA1c        1.0009
 Chol         1.0009
 TG           1.0009
 HDL          1.0009
 LDL          1.0009
 VLDL         1.0009
 BMI          1.0009
 CLASS        0.0000
 dtype: float64)